services:
  webapp:
    ports:
      - "127.0.0.1:8000:8000/tcp"
    volumes:
      - static-data:/usr/src/app/static
    env_file: ./prod.env
    restart: unless-stopped

volumes:
  static-data:
    external: true
    name: anubis-static