services:
  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - back-tier
  webapp:
    image: anubis/webapp
    build: ./src
    depends_on:
      - db
    volumes:
      - ${HOME}/.ssh:/root/.ssh
    networks:
      - back-tier

volumes:
  db-data:

networks:
  back-tier: