# Generated by Django 3.2.5 on 2021-11-16 16:01

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField()),
                ('user_id', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[a-z0-9]{6,12}$')])),
                ('phone_number', models.CharField(blank=True, max_length=16)),
                ('status_code', models.CharField(blank=True, max_length=3)),
                ('raw_response', models.TextField(blank=True)),
                ('error_msg', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
